#define HashMap unordered_map
#define ChunkAmount 5
#define TileAmount 5
#define TileWidth 100
#define TileHeight (TileWidth/2)
#define ChunkWidth (TileWidth*TileAmount)
#define ChunkHeight (TileHeight*TileAmount)
#define RenderDistance 2
#define CollisionDistance 1